# Generated by Django 4.2.7 on 2023-11-21 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_pleasant', models.BooleanField(default=False, verbose_name='Полезная привычка?')),
                ('is_public', models.BooleanField(default=False, verbose_name='Для общего доступа?')),
                ('place', models.CharField(max_length=250, verbose_name='Место')),
                ('action', models.CharField(max_length=1000, verbose_name='Действие')),
                ('lead_time', models.PositiveSmallIntegerField(verbose_name='Время, необходимое для выполнения привычки')),
                ('reward', models.TextField(blank=True, null=True, verbose_name='Вознаграждение')),
                ('qty_per_period', models.PositiveSmallIntegerField(verbose_name='Количество раз в период')),
                ('period', models.CharField(choices=[(0, 'В день'), (1, 'В час'), (2, 'В минуту'), (3, 'В секунду')], default=0, max_length=150, verbose_name='Период')),
                ('start_time', models.DateTimeField(verbose_name='Дата и время первого выполнения привычки')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('relating_pleasant_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_habits', to='habits.habit', verbose_name='Связанная приятная привычка')),
            ],
        ),
    ]
