# Generated by Django 4.2.7 on 2023-11-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='is_pleasant',
            field=models.BooleanField(default=False, verbose_name='Приятная привычка?'),
        ),
    ]
