# Generated by Django 4.2.7 on 2023-11-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_alter_habit_is_pleasant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='period',
            field=models.CharField(choices=[(0, 'В день'), (1, 'В час'), (2, 'В минуту'), (3, 'В секунду')], default=0, max_length=150, verbose_name='Интервал'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='qty_per_period',
            field=models.PositiveSmallIntegerField(verbose_name='Каждые (указать кол-во интервалов)'),
        ),
    ]
