# Generated by Django 4.2.7 on 2023-11-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_alter_habit_period_alter_habit_qty_per_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='lead_time',
            field=models.PositiveSmallIntegerField(verbose_name='Кол-во секунд, необходимое для выполнения привычки'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='period',
            field=models.CharField(choices=[(0, 'дней'), (1, 'часов'), (2, 'минут'), (3, 'секунд')], default=0, max_length=150, verbose_name='Интервал'),
        ),
    ]
