# Generated by Django 4.2.7 on 2023-11-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_alter_habit_lead_time_alter_habit_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='qty_per_period',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Каждые (указать кол-во интервалов)'),
        ),
    ]
