# Generated by Django 4.2.7 on 2023-11-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0009_alter_habit_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время первого выполнения привычки'),
        ),
    ]
