# Generated by Django 4.2.7 on 2023-11-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0010_alter_habit_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='start_time',
            field=models.DateTimeField(verbose_name='Дата и время первого выполнения привычки'),
        ),
    ]
