# Generated by Django 4.2.7 on 2023-11-22 16:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0011_alter_habit_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время первого выполнения привычки'),
        ),
    ]
